// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file proto/echo/echo.proto (package echo, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/echo/echo.proto.
 */
export const file_proto_echo_echo: GenFile = /*@__PURE__*/
  fileDesc("ChVwcm90by9lY2hvL2VjaG8ucHJvdG8SBGVjaG8iHgoLRWNob1JlcXVlc3QSDwoHbWVzc2FnZRgBIAEoCSIfCgxFY2hvUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCTI8CgtFY2hvU2VydmljZRItCgRFY2hvEhEuZWNoby5FY2hvUmVxdWVzdBoSLmVjaG8uRWNob1Jlc3BvbnNlQkBaPmdpdGh1Yi5jb20vR2Fiby1kaXYvYmluZ28vcGFja2FnZXMvcHJvdG9idWYvZ28vcHJvdG8vZWNobztlY2hvYgZwcm90bzM");

/**
 * @generated from message echo.EchoRequest
 */
export type EchoRequest = Message<"echo.EchoRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message echo.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export const EchoRequestSchema: GenMessage<EchoRequest> = /*@__PURE__*/
  messageDesc(file_proto_echo_echo, 0);

/**
 * @generated from message echo.EchoResponse
 */
export type EchoResponse = Message<"echo.EchoResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message echo.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export const EchoResponseSchema: GenMessage<EchoResponse> = /*@__PURE__*/
  messageDesc(file_proto_echo_echo, 1);

/**
 * @generated from service echo.EchoService
 */
export const EchoService: GenService<{
  /**
   * @generated from rpc echo.EchoService.Echo
   */
  echo: {
    methodKind: "unary";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_echo_echo, 0);

